swagger: '2.0'
info:
  title: Skydot Transfer
  description: Money transfer
  version: 1.0.0
host: localhost:8080
schemes:
  - https
  - http
basePath: /
paths:
  /transfer:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      description:
        Transfers money.
      parameters:
        - in: body
          name: TransferRequest
          description: Transfer request data
          schema:
            $ref: '#/definitions/TransferRequest'
      responses:
        '200':
          description: Transfer response data
          schema:
            $ref: '#/definitions/TransferResponse'
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/TransferResponse'
definitions:
  TransferRequest:
    type: object
    description: Account Information
    properties:
      user_id:
        description: User Id
        type: string
      from_account:
        description: Transfer from account
        type: string
      to_account:
        description: Transfer to account
        type: string
      amount:
        description: Amount to transfer
        type: integer
      currency:
        description: Currency of transfer
        type: string
    example:
      {
        "user_id": "me",
        "from_account": 54321,
        "to_account": 12345,
        "amount": 10.00,
        "currency": "CAD"
      }
  TransferResponse:
    type: object
    description: Transfer Response
    properties:
      status:
        description: HTTP status
        type: integer
      error:
        description: The error code
        type: string
      message:
        description: Error response reason
        type: string