apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  selector:
    app: web-app
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: web-app
        tier: frontend
        track: stable
    spec:
      containers:
      - name: nginx
        image: "lex13/web-app"
      nodeSelector:
        micro: app