apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
  selector:
    app: auth-app
    tier: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: auth-app
spec:
  selector:
    app: auth-app
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  externalIPs:
  - 52.235.20.174
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: auth-app
spec:
  selector:
    matchLabels:
      app: auth-app
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-app
        tier: frontend
        track: stable
    spec:
      containers:
      - name: auth-app
        image: "lex13/auth-app"
      - name: redis
        image: "lex13/redis"
        ports:
        - containerPort: 6379
          name: redis
      nodeSelector:
        micro: app