apiVersion: v1
kind: Service
metadata:
  name: auth-app
spec:
  selector:
    app: auth-app
    tier: frontend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: auth-app
spec:
  selector:
    matchLabels:
      app: auth-app
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-app
        tier: frontend
        track: stable
    spec:
      containers:
      - name: nginx
        image: "lex13/auth-app"