apiVersion: v1
kind: Service
metadata:
  name: balance-skydot
spec:
  selector:
    app: mobile-app
    tier: frontend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
