apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bill-payee-service-java
spec:
  selector:
    matchLabels:
      app: bill-payee-service-java
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: bill-payee-service-java
        tier: backend
        track: stable
    spec:
      containers:
        - name: bill-payee-service-java
          image: "lex13/bill-payee-service-java"
          ports:
            - name: http
              containerPort: 8080
      nodeSelector:
        lang: java
---
kind: Service
apiVersion: v1
metadata:
  name: bill-payee-service-java
spec:
  selector:
    app: bill-payee-service-java
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http