kubectl create -f verify-service-cplus.yaml
kubectl create -f verify-service-python.yaml
kubectl create -f account-details-service-python.yaml	
kubectl create -f account-summary-service-python.yaml	
kubectl create -f bill-payee-service-java.yaml		
kubectl create -f bill-payee-service-javascript.yaml	
kubectl create -f bill-payee-service-python.yaml		
kubectl create -f bill-payment-service-javascript.yaml	
kubectl create -f bill-payment-service-python.yaml	
kubectl create -f bill-payment-service-java.yaml		
kubectl create -f bill-payment-service-cplus.yaml		
kubectl create -f create-service-python.yaml		
kubectl create -f create-service-cplus.yaml		
kubectl create -f delete-service-python.yaml		
kubectl create -f delete-service-cplus.yaml		
kubectl create -f transfer-service-python.yaml
kubectl create -f transfer-service-cplus.yaml
kubectl create -f transfer-service-java.yaml
kubectl create -f transfer-service-javascript.yaml
kubectl create -f mobile-app.yaml
kubectl create -f auth-app.yaml				
kubectl create -f host-gateway.yaml	
kubectl create -f jumpod.yaml
